name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Emacs (headless)
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs-nox

      - name: Show Emacs version
        run: emacs --version

      - name: Cache ELPA
        uses: actions/cache@v4
        with:
          path: ~/.emacs.d/elpa
          key: elpa-${{ runner.os }}-${{ hashFiles('**/*.el') }}-${{ steps.emacsver.outputs.ver || 'default' }}
          restore-keys: |
            elpa-${{ runner.os }}-

      - name: Run ERT tests (install deps if missing)
        run: |
          emacs -Q --batch \
            --eval "(progn
                      (require 'package)
                      (add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)
                      (package-initialize)
                      (unless (package-installed-p 'async)
                        (package-refresh-contents)
                        (package-install 'async)))" \
            -L . \
            -l praise.el \
            -l praise-test.el \
            -f ert-run-tests-batch-and-exit
